# Notebook : MLPM retreat Valencia

```{r setup, message = FALSE}
knitr::opts_chunk$set(error = FALSE, warning = FALSE, fig.width = 12, fig.height = 8, dev = "pdf", fig.keep = "high", fig.path = "figure/", cache.path = "cache/")
set.seed(35875954)

library(caret)
library(pcaPP)
library(kernlab)
source('predictors.R')
```

# Load data

```{r data, cache = TRUE}
# read in datasets
datapath <- '../Data/RNASeq/'
fnames <- list.files(path = datapath, pattern = '[.]csv$', full.names = FALSE)
objnames <- gsub('[.]csv$', '', fnames)
for (obj in objnames) {
  x <- read.csv(paste0(datapath, obj, '.csv'), sep = ',', header = TRUE, row.names = 1)
  rownames(x) <- paste0('X_', gsub('[^[:alnum:]_]', '_', rownames(x)))
  if (!grepl('design', obj)) x <- t(x) # observations in rows and features in col
  assign(obj, x)
  cat('==============> ', obj, '<==============\n')
  print(dim(get(obj)))
}
# just some checking on samplelist
xlist <- objnames[!grepl('design', objnames)]
for (xname in xlist) {
  stopifnot(isTRUE(all.equal(rownames(get(xname)), as.character(as.character(rnaseq_design$SampleID_RNASeq)))))
}
# generate train2test
trainidx <- grep('train', rnaseq_design$NA., ignore.case = TRUE)
table(rnaseq_design$NA.)
# generate labels
effect.grps <- as.factor(rnaseq_design$Effect)
ylist <- c('effect.grps')
```

# SVM

```{r svm, cache = TRUE, message = FALSE}
kf <- 'linear'
res <- list()
i <- 1
for (xname in xlist) {
  for (yname in ylist) {
    res[[i]] <- perfSVM(model = paste('ksvm', kf, sep = '_AAA_'), prefix = paste(xname, yname, sep = '_AAA_'), 
                        xdata = get(xname), grp = get(yname), kf = kf, tr2tstFolds = trainidx)
    i <- i + 1
  }
}
```

# Plot

```{r plot}
dd <- data.frame()
for (i in seq(length(res))) {
  dd <- rbind(dd, 
              data.frame(model = res[[i]]$model, prefix = res[[i]]$prefix, kf = res[[i]]$kf, acc = res[[i]]$acc))
}
ggplot(dd, aes(x = prefix, y = acc)) + 
  geom_bar(aes(fill = prefix), stat="identity") + 
  theme(axis.text.x = element_blank())
```

# Session info

```{r session_info}
devtools::session_info()
```

